### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by JamesVStone** [ojoeth/school-work-c#1]
i wanted to open this issue because you put rocks in my bag

**Comment by ojoeth** [comment]
not a bug

**Comment by ojoeth** [comment]
**not a bug**

**Comment by ojoeth** [comment]
these are rocks, not bugs.

**Comment by JamesVStone** [comment]
the rocks are bugging me

**Comment by ojoeth** [comment]
that's a personal issue

**Comment by ojoeth** [comment]
still not a bug

**Comment by ojoeth** [comment]
how are you reopining the issue?
