### ISSUE TITLE
wow smh rn

### ISSUE THREAD

**Issue by JamesVStone** [ojoeth/school-work-c#3]
https://github.com/ojoeth/school-work-c/blob/1ff9195d1d3e7f09d5eac87252c4557b22c10db7/week-4/ex3.c#L18

u used `gets()` again smh. Also, the fuck kinda formatting is that; newline after a semi.

**Comment by ojoeth** [comment]
this is a school work repo, that's how they were teaching. blame compsci not me

**Comment by JamesVStone** [comment]
also you're not forgiven for putting rocks in my bag

**Comment by JamesVStone** [comment]
> this is a school work repo, that's how they were teaching. blame compsci not me

be accountable for your own C sir.
